/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package nl.knaw.huc.di.rd.tag.tagml.lsp

class App {


    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
//    val rpcServer = JsonRpcServer()
//    val tagmlService = LSPService()
//    val request = "{}"
//    var response = rpcServer.handle(request,tagmlService);
//    println(response)

    println(App().greeting)
}
